name: Build Windows

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: install restsdk
        run: vcpkg install cpprestsdk cpprestsdk:x64-windows
      - name: cmake configure
        run: |
          md cmake-build-debug
          cd cmake-build-debug
          cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: cmake build
        run: |
          cd cmake-build-debug
          cmake --build . --target weatherpp
