name: MacOS Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: install restsdk
        run: brew install cpprestsdk
      - name: cmake configure
        run: |
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -G "CodeBlocks - Unix Makefiles" ..
      - name: cmake build
        run: |
          cd cmake-build-debug
          cmake --build . --target weatherpp
